### ISSUE TITLE
worldname placeholder not working in windows 8.1

### ISSUE THREAD

**Issue by meh1961** [nicoco007/MCBackup-3#21]
In windows 8.1 , the place holder for worldname gives DirectoryName instead of the actual name. The date and time in the backup name is correct. In the description of the backup on the right side of the window, the original name field shows the correct world name. This is Minecraft 1.8, and MC Backup 3.7.4.0

**Comment by nicoco007** [comment]
This is still an issue, why did you close it?

**Comment by meh1961** [comment]
sorry, I wasn't quite sure of how to correctly use this site to report issues.

**Comment by nicoco007** [comment]
That's okay :smile:

I'll try fixing this as soon as possible, I'm just very busy right now.
