### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by tractorcow** [nicoco007/MCBackup-3#34]
Do you have a guide for building from source? Can you provide source for your dependencies? E.g. `GettextSharp`? I assume that's a dot net port of gettext, but which specific library are you using?

**Comment by nicoco007** [comment]
I think everything except GettextSharp and Substrate are installed through NuGet. Substrate can be downloaded [from its GitHub repo](), but GettextSharp is a library I had built myself and never uploaded to GitHub; it's probably still lying around somewhere on my computer, so I can look once I get time.

**Comment by tractorcow** [comment]
That's great thanks @nicoco007 :)

**Comment by nicoco007** [comment]
Unfortunately I can no longer find the GettextSharp project so it looks like you'll have to either implement translation functionality through another 3rd-party library (e.g. https://github.com/VitaliiTsilnyk/NGettext) or remove it altogether. Sorry about that!

**Comment by tractorcow** [comment]
That's ok; I can hack around it :P

**Comment by tractorcow** [comment]
Marking closed as answered.
